export const strings = {
  blog: 'وبلاگ‌ها',
  'e-commerce': 'فروشگاهی',
  transport: 'حمل و نقل',
  job: 'کاریابی',
  news: 'اخبار',
  healthcare: 'سلامت',
  'software-as-a-service': 'نرم‌افزار',
  media: 'رسانه',
  event: 'رویداد',
  finance: 'مالی',
  provider: 'سرویس دهنده‌ها',
  messaging: 'پیام‌رسانی',
  reservation: 'رزرو',
  education: 'آموزشی',
  entertainment: 'سرگرمی',
  marketing: 'بازاریابی',
  information: 'اطلاعات و داده',
  advertisement: 'تبلیغات',
  travel: 'سفر',
  mobile: 'موبایل',
  design: 'طراحی',
  game: 'بازی',
  insurance: 'بیمه',
  map: 'نقشه',

  title: 'فهرست سایت‌ها / سرویس‌ها',
  service_name: `نام سرویس`,
  service_name_placeholder: `نام سرویس مورد نظر خود را بنویسید...`,
  service_status: 'وضعیت سرویس ها',
  service_category: `دسته بندی سرویس ها`,
  service_priority: `اولویت سرویس‌ها`,
  all_options: `همه موارد`,
  priority_all: `همه موارد`,
  priority_1: 'سرویس‌های که استفاده روزمره دارند',
  priority_2: 'سرویس‌های که استفاده روزمره ندارند',
  priority_3: 'سرویس‌های که کم کاربرد هستند',

  all: 'همه موارد',
  'easy-label': 'ساده',
  'medium-label': 'متوسط',
  'hard-label': 'سخت',
  'impossible-label': 'غیر‌ممکن',

  delete_account: `حذف حساب کاربری`,
  edit: 'تصحیح',
  edit_service_hint: `اطلاعات این بخش اشتباه است قصد اصلاح دارم`,
  participate_hint: 'شما هم مشارکت کنید',
  home_page_title: 'دایرکتوری حذف حساب‌های کاربری | حق فراموش شدن',
  home_page_description:
    'برای حذف حساب‌های کاربری خود در سرویس‌ها / اپلیکیشن‌ها / وب‌سایت‌ها می‌توانید از سرویس حق فراموش شدن استفاده کنید. این سرویس به شما این امکان را می‌دهد که از روش حذف حساب کاربری خود یا اکانت خود در بخش‌های مختلف اینترنت آگاه شوید.',
  do_twit: 'توییت کنید',
  comments: 'نظرات',
  sign_up_comment: `برای دسترسی به بخش نظرات لطفا ثبت نام کنید!`,
  email_address: 'آدرس ایمیل',
  sign_in_header: 'ورود',
  username_label: 'نام کاربری',
  password_label: 'رمز عبور',
  sign_up_button: 'ثبت نام',
  sign_in_link: 'حساب کاربری دارید؟ ورود',
  username_required: 'نام کاربری الزامی است.',
  email_required: 'ایمیل الزامی است.',
  email_invalid_format: 'فرمت ایمیل معتبر نیست.',
  password_required: 'رمز عبور الزامی است.',
  password_invalid_format:
    'رمز عبور باید شامل حداقل هشت کاراکتر، یک کاراکتر ویژه و یک حرف بزرگ باشد.',
  add_comment: 'ارسال نظر',
  write_comment:'نظر خود را بنویسید'
};
