export const strings = {
  blog: 'وبلاگ‌ها',
  'e-commerce': 'فروشگاهی',
  transport: 'حمل و نقل',
  job: 'کاریابی',
  news: 'اخبار',
  healthcare: 'سلامت',
  'software-as-a-service': 'نرم‌افزار',
  media: 'رسانه',
  event: 'رویداد',
  finance: 'مالی',
  provider: 'سرویس دهنده‌ها',
  messaging: 'پیام‌رسانی',
  reservation: 'رزرو',
  education: 'آموزشی',
  entertainment: 'سرگرمی',
  marketing: 'بازاریابی',
  information: 'اطلاعات و داده',
  advertisement: 'تبلیغات',
  travel: 'سفر',
  mobile: 'موبایل',
  design: 'طراحی',
  game: 'بازی',
  insurance: 'بیمه',
  map: 'نقشه',

  title: 'فهرست سایت‌ها / سرویس‌ها',
  service_name: `نام سرویس`,
  service_name_placeholder: `نام سرویس مورد نظر خود را بنویسید...`,
  service_status: 'وضعیت سرویس ها',
  service_category: `دسته بندی سرویس ها`,
  service_priority: `اولویت سرویس‌ها`,
  all_options: `همه موارد`,
  priority_all: `همه موارد`,
  priority_1: 'سرویس‌های که استفاده روزمره دارند',
  priority_2: 'سرویس‌های که استفاده روزمره ندارند',
  priority_3: 'سرویس‌های که کم کاربرد هستند',

  all: 'همه موارد',
  'easy-label': 'ساده',
  'medium-label': 'متوسط',
  'hard-label': 'سخت',
  'impossible-label': 'غیر‌ممکن',
};
